-- MySQL Script generated by MySQL Workbench
-- Mon Jun 28 12:05:35 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema work-trial-ecommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema work-trial-ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `work-trial-ecommerce` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `work-trial-ecommerce` ;

-- -----------------------------------------------------
-- Table `work-trial-ecommerce`.`customeraddress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `work-trial-ecommerce`.`customer_address`
(
    `id`           VARCHAR(36) NOT NULL,
    `street`       VARCHAR(65) NOT NULL,
    `house_number` VARCHAR(20) NOT NULL,
    `state`        VARCHAR(15) NOT NULL,
    `country`      VARCHAR(25) NOT NULL,
    `city`         VARCHAR(35) NOT NULL,
    `zip_code`     VARCHAR(15) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `work-trial-ecommerce`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `work-trial-ecommerce`.`customer`
(
    `id`                  VARCHAR(36) NOT NULL,
    `last_name`                VARCHAR(55) NOT NULL,
    `first_name`          VARCHAR(55) NOT NULL,
    `birthdate`           DATE        NOT NULL,
    `job_title`           VARCHAR(55) NOT NULL,
    `category`            VARCHAR(45) NOT NULL,
    `email_address`       VARCHAR(45) NOT NULL,
    `customer_address_id` VARCHAR(36) NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `customer_to_customer_address`
        FOREIGN KEY (`customer_address_id`) REFERENCES `work-trial-ecommerce`.`customer_address` (`id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `work-trial-ecommerce`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `work-trial-ecommerce`.`product`
(
    `id`          VARCHAR(36) NOT NULL,
    `label`       VARCHAR(45) NOT NULL,
    `description` VARCHAR(45) NULL DEFAULT NULL,
    `price`       FLOAT       NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci;


-- -----------------------------------------------------
-- Table `work-trial-ecommerce`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `work-trial-ecommerce`.`order`
(
    `id`              VARCHAR(36)  NOT NULL,
    `customer_id`     VARCHAR(55)  NOT NULL,
    `additional_info` VARCHAR(120) NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `order_to_customer`
        FOREIGN KEY (`customer_id`)
            REFERENCES `work-trial-ecommerce`.`customer` (`id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS `work-trial-ecommerce`.`order_product`
(
    `id`         VARCHAR(36) NOT NULL,
    `order_id`   VARCHAR(36) NOT NULL,
    `product_id` VARCHAR(36) NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `order_product_to_order` FOREIGN KEY (`order_id`)
        REFERENCES `work-trial-ecommerce`.`order` (`id`),
    CONSTRAINT `order_product_to_product` FOREIGN KEY (`product_id`)
        REFERENCES `work-trial-ecommerce`.`product` (`id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;